name: translate

on: [push]

jobs:
  update-translations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Update translation
      run: |
        git config --global user.name "${{ secrets.NAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        npm install @userdashboard/dashboard --no-save
        mkdir project
        cd project
        git clone https://github.com/userdashboard/dashboard.git
        git clone https://github.com/userdashboard/organizations.git
        git clone https://github.com/userdashboard/stripe-connect.git
        git clone https://github.com/userdashboard/stripe-subscriptions.git
        cd dashboard
        npm install
        cd ../..
        wget https://git.io/trans
        chmod +x ./trans
        sudo mv trans /usr/local/bin
        for LOCALE in `cat languages`; do
          node localize.js "$LOCALE"
        done
        git pull
    - name: Commit updated translation cache
      uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Automatically regenerated against current version
        branch: ${{ github.head_ref }}
        commit_options: "--no-verify --signoff"
        repository: .
        push_options: "--force"
    - name: Deploy updated translations to Dashboard
      uses: peaceiris/actions-gh-pages@v3
      with: 
        external_repository: "userdashboard/dashboard"
        personal_token: ${{ secrets.LOCALIZATION_PAT }}
        publish_dir: ./project/dashboard
        publish_branch: master
        keep_files: true
    - name: Deploy updated translations to Organizations module
      uses: peaceiris/actions-gh-pages@v3
      with: 
        external_repository: "userdashboard/dashboard"
        personal_token: ${{ secrets.LOCALIZATION_PAT }}
        publish_dir: ./project/organizations
        publish_branch: master
        keep_files: true
    - name: Deploy updated translations to Stripe Connect module
      uses: peaceiris/actions-gh-pages@v3
      with: 
        external_repository: "userdashboard/dashboard"
        personal_token: ${{ secrets.LOCALIZATION_PAT }}
        publish_dir: ./project/stripe-conect
        publish_branch: master
        keep_files: true
    - name: Deploy updated translations to Stripe Subscriptions module
      uses: peaceiris/actions-gh-pages@v3
      with: 
        external_repository: "userdashboard/dashboard"
        personal_token: ${{ secrets.LOCALIZATION_PAT }}
        publish_dir: ./project/stripe-subscriptions
        publish_branch: master
        keep_files: true
